const INCREASE_LOADING = 'INCREASE_LOADING'
const DECREASE_LOADING = 'DECREASE_LOADING'
const GET_CUSTOMERS = 'GET_CUSTOMERS'
const GET_ORDERS = 'GET_ORDERS'
const SET_SELECTED_CUSTOMER = 'SET_SELECTED_CUSTOMER'

export {
  INCREASE_LOADING,
  DECREASE_LOADING,
  GET_CUSTOMERS,
  GET_ORDERS,
  SET_SELECTED_CUSTOMER,
}
